// Generated by apifier 0.0.1 on 2026-05-19T07:42:11.034Z from https://widget.example.com/openapi.json.
// Mapping schema_version: 1. Do not edit by hand.
// Service: Widgets API
// Init:
//   const client = new WidgetsApiClient({ baseUrl: "https://api.widget.example.com/v1" });
//   client.setBearerToken(process.env.WIDGETS_API_TOKEN ?? '');
//   const result = await client.<methodName>(args);

/** Standard error envelope. */
export interface ApiError {
  /** Stable machine-readable error code. */
  code: string;
  /** Human-readable message. */
  message: string;
}

/** A widget. */
export interface Widget {
  /** Widget identifier. */
  id: string;
  /** Widget color. */
  color: "red" | "green" | "blue";
  /** Widget size in mm. */
  size?: number;
}

/** Payload to create a widget. */
export interface WidgetCreate {
  color: "red" | "green" | "blue";
  size?: number;
}

/** Base class for all apifier client errors. */
export class ApifierClientError extends Error {
  constructor(public readonly body: string, public readonly status?: number) {
    super(`HTTP ${status ?? '?'}: ${body}`);
    this.name = 'ApifierClientError';
  }
}

/** Network or transport failure. */
export class ApifierNetworkError extends ApifierClientError {
  constructor(message: string) { super(message); this.name = 'ApifierNetworkError'; }
}

/** Request timeout. */
export class ApifierTimeoutError extends ApifierClientError {
  constructor(message: string) { super(message); this.name = 'ApifierTimeoutError'; }
}

/** Any non-2xx HTTP response (4xx or 5xx). */
export class ApifierHttpError extends ApifierClientError {
  constructor(body: string, status: number) { super(body, status); this.name = 'ApifierHttpError'; }
}

/** 4xx client error. */
export class ApifierClientHttpError extends ApifierHttpError {
  constructor(body: string, status: number) { super(body, status); this.name = 'ApifierClientHttpError'; }
}

/** 400 Validation error. */
export class ApifierValidationError extends ApifierClientHttpError {
  constructor(body: string) { super(body, 400); this.name = 'ApifierValidationError'; }
}

/** 401 Authentication error. */
export class ApifierAuthenticationError extends ApifierClientHttpError {
  constructor(body: string) { super(body, 401); this.name = 'ApifierAuthenticationError'; }
}

/** 403 Authorization error. */
export class ApifierAuthorizationError extends ApifierClientHttpError {
  constructor(body: string) { super(body, 403); this.name = 'ApifierAuthorizationError'; }
}

/** 404 Not found error. */
export class ApifierNotFoundError extends ApifierClientHttpError {
  constructor(body: string) { super(body, 404); this.name = 'ApifierNotFoundError'; }
}

/** 409 Conflict error. */
export class ApifierConflictError extends ApifierClientHttpError {
  constructor(body: string) { super(body, 409); this.name = 'ApifierConflictError'; }
}

/** 5xx server error. */
export class ApifierServerError extends ApifierHttpError {
  constructor(body: string, status: number) { super(body, status); this.name = 'ApifierServerError'; }
}

/** Response body did not match declared schema. */
export class ApifierDecodeError extends ApifierClientError {
  constructor(message: string) { super(message); this.name = 'ApifierDecodeError'; }
}

/** Widgets API client generated from apifier-mapping v1. */
export class WidgetsApiClient {
  private _baseUrl: string;
  private _bearerToken: string | undefined;

  constructor(opts: { baseUrl?: string } = {}) {
    this._baseUrl = opts.baseUrl ?? "https://api.widget.example.com/v1";
    // Remove trailing slash for consistent URL construction
    if (this._baseUrl.endsWith('/')) this._baseUrl = this._baseUrl.slice(0, -1);
  }

  /** Set the Bearer token for HTTP bearer authentication. */
  setBearerToken(token: string): void {
    this._bearerToken = token;
  }

  /** Get a widget by id. */
  async getWidget(args: { id: string } = {} as { id: string }): Promise<Widget> {
    let _url = `${this._baseUrl}/widgets/${encodeURIComponent(String(args.id))}`;
    const _headers: Record<string, string> = {};
    if (this._bearerToken) _headers['Authorization'] = `Bearer ${this._bearerToken}`;
    const _res = await fetch(_url, { method: "GET", headers: _headers });
    if (_res.status === 200) return _res.json() as Promise<Widget>;
    if (_res.status === 404) throw new ApifierNotFoundError(await _res.text());
    if (_res.status >= 200 && _res.status < 300) return _res.json() as Promise<Widget>;
    if (_res.status >= 400 && _res.status < 500) throw new ApifierClientError(await _res.text(), _res.status);
    throw new ApifierServerError(await _res.text(), _res.status);
  }

  /** Create a widget. */
  async createWidget(args: { body: WidgetCreate } = {} as { body: WidgetCreate }): Promise<Widget> {
    let _url = `${this._baseUrl}/widgets`;
    const _headers: Record<string, string> = {};
    if (this._bearerToken) _headers['Authorization'] = `Bearer ${this._bearerToken}`;
    _headers['Content-Type'] = 'application/json';
    const _res = await fetch(_url, { method: "POST", headers: _headers, body: JSON.stringify(args.body) });
    if (_res.status === 201) return _res.json() as Promise<Widget>;
    if (_res.status === 400) throw new ApifierValidationError(await _res.text());
    if (_res.status >= 200 && _res.status < 300) return _res.json() as Promise<Widget>;
    if (_res.status >= 400 && _res.status < 500) throw new ApifierClientError(await _res.text(), _res.status);
    throw new ApifierServerError(await _res.text(), _res.status);
  }
}

export default WidgetsApiClient;
