#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Generated by apifier; do not edit by hand.
# ---------------------------------------------------------------------------
# Service:        Widgets API
# Source:         https://widget.example.com/openapi.json
# sha256:         f7c1e8b2a3d4e5f6071829aabbccddeeff00112233445566778899aabbccddeeff
# fetched_at:     2026-05-19T07:42:11.034Z
# schema_version: 1
# apifier:        0.0.1
#
# Quick start:
#   source ./client.sh
#   export APIFIER_BEARER_TOKEN=<your-token>
#   # Call an endpoint (env-style parameter passing):
#   #   widget_id=abc123 apifier__get__widgets__id
#   # Requires bash 4+. Not POSIX-sh compatible.
# ---------------------------------------------------------------------------
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration — override via environment before sourcing or calling functions
# ---------------------------------------------------------------------------
: "${APIFIER_BASE_URL:=https://api.widget.example.com/v1}"
: "${APIFIER_BEARER_TOKEN:=}"
: "${APIFIER_TIMEOUT_SEC:=30}"
: "${APIFIER_CURL_OPTS:=--silent --show-error --fail}"

# apifier__auth_headers — echo curl flags for header-based auth
apifier__auth_headers() {
  local _h=()
  [[ -n "${APIFIER_BEARER_TOKEN:-}" ]] && _h+=(-H "Authorization: Bearer ${APIFIER_BEARER_TOKEN}")
  if [[ ${#_h[@]} -gt 0 ]]; then printf '%s\n' "${_h[@]}"; fi
}

# ---------------------------------------------------------------------------
# Model reference (bash has no struct types — shown for documentation only)
# ---------------------------------------------------------------------------
# ApiError — Standard error envelope.
#   .code (required) — Stable machine-readable error code.
#   .message (required) — Human-readable message.
# Widget — A widget.
#   .id (required) — Widget identifier.
#   .color (required) — Widget color.
#   .size (optional) — Widget size in mm.
# WidgetCreate — Payload to create a widget.
#   .color (required)
#   .size (optional)
# ---------------------------------------------------------------------------

# apifier__get__widgets_id — Get a widget by id.
# Usage: id=<value> apifier__get__widgets_id
apifier__get__widgets_id() {
  : "${id:?id is required for apifier__get__widgets_id}"
  local _url="${APIFIER_BASE_URL}/widgets/${id}"
  local _auth_args=()
  while IFS= read -r _line; do
    [[ -n "${_line:-}" ]] && _auth_args+=("${_line}")
  done < <(apifier__auth_headers)
  local _body_args=()
  local _cmd=(curl --request GET)
  local _opts_arr
  # shellcheck disable=SC2086
  IFS=" " read -ra _opts_arr <<< "${APIFIER_CURL_OPTS}"
  _cmd+=("${_opts_arr[@]}")
  _cmd+=(--max-time "${APIFIER_TIMEOUT_SEC}")
  if [[ ${#_auth_args[@]} -gt 0 ]]; then _cmd+=("${_auth_args[@]}"); fi
  if [[ ${#_body_args[@]} -gt 0 ]]; then _cmd+=("${_body_args[@]}"); fi
  _cmd+=("${_url}")
  "${_cmd[@]}"
}

# apifier__post__widgets — Create a widget.
# Usage:  apifier_body=<json> apifier__post__widgets
apifier__post__widgets() {
  local _url="${APIFIER_BASE_URL}/widgets"
  local _auth_args=()
  while IFS= read -r _line; do
    [[ -n "${_line:-}" ]] && _auth_args+=("${_line}")
  done < <(apifier__auth_headers)
  local _body_args=()
  _body_args+=(-H "Content-Type: application/json")
  if [[ -n "${apifier_body_file:-}" ]]; then
    _body_args+=(--data "@${apifier_body_file}")
  elif [[ -n "${apifier_body:-}" ]]; then
    _body_args+=(--data "${apifier_body}")
  fi
  local _cmd=(curl --request POST)
  local _opts_arr
  # shellcheck disable=SC2086
  IFS=" " read -ra _opts_arr <<< "${APIFIER_CURL_OPTS}"
  _cmd+=("${_opts_arr[@]}")
  _cmd+=(--max-time "${APIFIER_TIMEOUT_SEC}")
  if [[ ${#_auth_args[@]} -gt 0 ]]; then _cmd+=("${_auth_args[@]}"); fi
  if [[ ${#_body_args[@]} -gt 0 ]]; then _cmd+=("${_body_args[@]}"); fi
  _cmd+=("${_url}")
  "${_cmd[@]}"
}
