"""
Generated by apifier 0.0.1 on 2026-05-19T07:42:11.034Z from https://widget.example.com/openapi.json.
Mapping schema_version: 1. Do not edit by hand.
Service: Widgets API

Quick start:
    client = WidgetsApiClient(base_url="https://api.widget.example.com/v1")
    import os; client.set_bearer_token(os.environ.get('WIDGETS_API_TOKEN', ''))
    result = client.<method_name>(...)
"""

# Requires: pip install requests
from __future__ import annotations
import urllib.parse
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Union

import requests

# Standard error envelope.
@dataclass
class ApiError:
    # Stable machine-readable error code.
    code: str
    # Human-readable message.
    message: str

# A widget.
@dataclass
class Widget:
    # Widget identifier.
    id: str
    # Widget color.
    color: str
    # Widget size in mm.
    size: Optional[int] = None

# Payload to create a widget.
@dataclass
class WidgetCreate:
    color: str
    size: Optional[int] = None

class ApifierClientError(Exception):
    """Base class for all apifier client errors."""

    def __init__(self, message: str, status_code: Optional[int] = None) -> None:
        super().__init__(message)
        self.status_code = status_code


class ApifierBadRequestError(ApifierClientError):
    """400 Bad request error."""


class ApifierAuthenticationError(ApifierClientError):
    """401 Authentication error."""


class ApifierAuthorizationError(ApifierClientError):
    """403 Authorization error."""


class ApifierNotFoundError(ApifierClientError):
    """404 Not found error."""


class ApifierConflictError(ApifierClientError):
    """409 Conflict error."""


class ApifierValidationError(ApifierClientError):
    """4xx fallback validation error."""


class ApifierServerError(ApifierClientError):
    """5xx server error."""


class WidgetsApiClient:
    """Widgets API client generated from apifier-mapping v1."""

    def __init__(self, base_url: Optional[str] = None) -> None:
        self._base_url: str = base_url if base_url is not None else "https://api.widget.example.com/v1"
        # Remove trailing slash for consistent URL construction
        if self._base_url.endswith('/'):
            self._base_url = self._base_url[:-1]
        self._bearer_token: Optional[str] = None

    def set_bearer_token(self, token: str) -> None:
        """Set the Bearer token for HTTP bearer authentication."""
        self._bearer_token = token

    def get_widget(self, *, id: str) -> Widget:
        """Get a widget by id."""
        _url = f"{self._base_url}/widgets/{urllib.parse.quote(str(id), safe='')}"
        _headers: Dict[str, str] = {}
        if self._bearer_token:
            _headers['Authorization'] = f'Bearer {self._bearer_token}'
        _resp = requests.request(method="GET", url=_url, headers=_headers)
        if _resp.status_code == 200:
            return _resp.json()
        if _resp.status_code == 404:
            raise ApifierNotFoundError(_resp.text, 404)
        if 200 <= _resp.status_code < 300:
            if "json" in _resp.headers.get("content-type", "").lower():
                return _resp.json()
            return _resp.text
        if 400 <= _resp.status_code < 500:
            raise ApifierClientError(_resp.text, _resp.status_code)
        raise ApifierServerError(_resp.text, _resp.status_code)

    def create_widget(self, *, body: WidgetCreate) -> Widget:
        """Create a widget."""
        _url = f"{self._base_url}/widgets"
        _headers: Dict[str, str] = {}
        if self._bearer_token:
            _headers['Authorization'] = f'Bearer {self._bearer_token}'
        _headers['Content-Type'] = 'application/json'
        _resp = requests.request(method="POST", url=_url, headers=_headers, json=body)
        if _resp.status_code == 201:
            return _resp.json()
        if _resp.status_code == 400:
            raise ApifierBadRequestError(_resp.text, 400)
        if 200 <= _resp.status_code < 300:
            if "json" in _resp.headers.get("content-type", "").lower():
                return _resp.json()
            return _resp.text
        if 400 <= _resp.status_code < 500:
            raise ApifierClientError(_resp.text, _resp.status_code)
        raise ApifierServerError(_resp.text, _resp.status_code)

__all__ = ["ApiError", "ApifierAuthenticationError", "ApifierAuthorizationError", "ApifierBadRequestError", "ApifierClientError", "ApifierConflictError", "ApifierNotFoundError", "ApifierServerError", "ApifierValidationError", "Widget", "WidgetCreate", "WidgetsApiClient"]
