// Code generated by apifier; DO NOT EDIT.
//
// Generated by apifier 0.0.1 on 2026-05-19T07:42:11.034Z from https://widget.example.com/openapi.json.
// Mapping schema_version: 1. sha256: f7c1e8b2a3d4e5f6071829aabbccddeeff00112233445566778899aabbccddeeff.
// Service: Widgets API
//
// Init:
//   client := NewWidgetsApiClient("https://api.widget.example.com/v1")
//   client.SetBearerToken(os.Getenv("WIDGETS_API_TOKEN"))
//   result, err := client.<MethodName>(ctx, ...)

package widgetsapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"
)

// ApifierClientError is the base error type for all apifier client errors.
type ApifierClientError struct {
	StatusCode int
	Body       string
}

func (e *ApifierClientError) Error() string {
	return fmt.Sprintf("apifier: HTTP %d: %s", e.StatusCode, e.Body)
}

// ErrApifierClientErr is a sentinel error for errors.Is consumers.
var ErrApifierClientErr = errors.New("apifier client error")

// ApifierBadRequestError represents a 400 Bad Request response.
type ApifierBadRequestError struct{ ApifierClientError }

// ApifierAuthenticationError represents a 401 Unauthorized response.
type ApifierAuthenticationError struct{ ApifierClientError }

// ApifierAuthorizationError represents a 403 Forbidden response.
type ApifierAuthorizationError struct{ ApifierClientError }

// ApifierNotFoundError represents a 404 Not Found response.
type ApifierNotFoundError struct{ ApifierClientError }

// ApifierConflictError represents a 409 Conflict response.
type ApifierConflictError struct{ ApifierClientError }

// ApifierValidationError represents a 4xx validation/client error.
type ApifierValidationError struct{ ApifierClientError }

// ApifierServerError represents a 5xx server error.
type ApifierServerError struct{ ApifierClientError }

// Standard error envelope.
type ApiError struct {
	// Stable machine-readable error code.
	Code string `json:"code"`
	// Human-readable message.
	Message string `json:"message"`
}

// A widget.
type Widget struct {
	// Widget identifier.
	Id string `json:"id"`
	// Widget color.
	Color string `json:"color"`
	// Widget size in mm.
	Size *int64 `json:"size,omitempty"`
}

// Payload to create a widget.
type WidgetCreate struct {
	Color string `json:"color"`
	Size *int64 `json:"size,omitempty"`
}

// WidgetsApiClient is the Widgets API client generated from apifier-mapping v1.
type WidgetsApiClient struct {
	baseURL    string
	httpClient *http.Client
	bearerToken string
}

// NewWidgetsApiClient creates a new WidgetsApiClient with the given base URL.
// If baseURL is empty, defaults to "https://api.widget.example.com/v1".
func NewWidgetsApiClient(baseURL string) *WidgetsApiClient {
	if baseURL == "" {
		baseURL = "https://api.widget.example.com/v1"
	}
	// Remove trailing slash for consistent URL construction
	for len(baseURL) > 0 && baseURL[len(baseURL)-1] == '/' {
		baseURL = baseURL[:len(baseURL)-1]
	}
	return &WidgetsApiClient{
		baseURL:    baseURL,
		httpClient: &http.Client{Timeout: 30 * time.Second},
	}
}

// WithHTTPClient returns a new WidgetsApiClient using the provided *http.Client.
func (c *WidgetsApiClient) WithHTTPClient(hc *http.Client) *WidgetsApiClient {
	c.httpClient = hc
	return c
}

// SetBearerToken sets the Bearer token for HTTP bearer authentication.
func (c *WidgetsApiClient) SetBearerToken(token string) {
	c.bearerToken = token
}

// GetWidgetArgs holds parameters for the GetWidget operation.
type GetWidgetArgs struct {
	// Widget id.
	Id string `json:"id"`
}

// GetWidget Get a widget by id.
func (c *WidgetsApiClient) GetWidget(ctx context.Context, args GetWidgetArgs) (Widget, error) {
	var _zero Widget
	_rawURL := c.baseURL + fmt.Sprintf("/widgets/%s", url.PathEscape(fmt.Sprintf("%v", args.Id)))
	req, _reqErr := http.NewRequestWithContext(ctx, "GET", _rawURL, nil)
	if _reqErr != nil {
		return _zero, fmt.Errorf("apifier: create request: %w", _reqErr)
	}
	if c.bearerToken != "" {
		req.Header.Set("Authorization", "Bearer "+c.bearerToken)
	}
	resp, _doErr := c.httpClient.Do(req)
	if _doErr != nil {
		return _zero, fmt.Errorf("apifier: do request: %w", _doErr)
	}
	defer resp.Body.Close()
	_body, _readErr := io.ReadAll(resp.Body)
	if _readErr != nil {
		return _zero, fmt.Errorf("apifier: read response body: %w", _readErr)
	}
	switch resp.StatusCode {
	case 200:
		var _result Widget
		if _jsonErr := json.Unmarshal(_body, &_result); _jsonErr != nil {
			return _zero, fmt.Errorf("apifier: decode response: %w", _jsonErr)
		}
		return _result, nil
	case 404:
		return _zero, &ApifierNotFoundError{ApifierClientError{StatusCode: 404, Body: string(_body)}}
	}
	// Generic fallback
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var _result Widget
		if _jsonErr := json.Unmarshal(_body, &_result); _jsonErr != nil {
			return _zero, fmt.Errorf("apifier: decode response: %w", _jsonErr)
		}
		return _result, nil
	}
	if resp.StatusCode >= 400 && resp.StatusCode < 500 {
		return _zero, &ApifierClientError{StatusCode: resp.StatusCode, Body: string(_body)}
	}
	return _zero, &ApifierServerError{ApifierClientError{StatusCode: resp.StatusCode, Body: string(_body)}}
}

// CreateWidgetArgs holds parameters for the CreateWidget operation.
type CreateWidgetArgs struct {
	Body WidgetCreate `json:"body"`
}

// CreateWidget Create a widget.
func (c *WidgetsApiClient) CreateWidget(ctx context.Context, args CreateWidgetArgs) (Widget, error) {
	var _zero Widget
	_rawURL := c.baseURL + "/widgets"
	var _bodyBuf bytes.Buffer
	if _encErr := json.NewEncoder(&_bodyBuf).Encode(args.Body); _encErr != nil {
		return _zero, fmt.Errorf("apifier: encode request body: %w", _encErr)
	}
	req, _reqErr := http.NewRequestWithContext(ctx, "POST", _rawURL, &_bodyBuf)
	if _reqErr != nil {
		return _zero, fmt.Errorf("apifier: create request: %w", _reqErr)
	}
	if c.bearerToken != "" {
		req.Header.Set("Authorization", "Bearer "+c.bearerToken)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, _doErr := c.httpClient.Do(req)
	if _doErr != nil {
		return _zero, fmt.Errorf("apifier: do request: %w", _doErr)
	}
	defer resp.Body.Close()
	_body, _readErr := io.ReadAll(resp.Body)
	if _readErr != nil {
		return _zero, fmt.Errorf("apifier: read response body: %w", _readErr)
	}
	switch resp.StatusCode {
	case 201:
		var _result Widget
		if _jsonErr := json.Unmarshal(_body, &_result); _jsonErr != nil {
			return _zero, fmt.Errorf("apifier: decode response: %w", _jsonErr)
		}
		return _result, nil
	case 400:
		return _zero, &ApifierBadRequestError{ApifierClientError{StatusCode: 400, Body: string(_body)}}
	}
	// Generic fallback
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var _result Widget
		if _jsonErr := json.Unmarshal(_body, &_result); _jsonErr != nil {
			return _zero, fmt.Errorf("apifier: decode response: %w", _jsonErr)
		}
		return _result, nil
	}
	if resp.StatusCode >= 400 && resp.StatusCode < 500 {
		return _zero, &ApifierClientError{StatusCode: resp.StatusCode, Body: string(_body)}
	}
	return _zero, &ApifierServerError{ApifierClientError{StatusCode: resp.StatusCode, Body: string(_body)}}
}
