'use strict';

// tests/unit/codegen-openapi-3.1.test.js — Unit tests for lib/codegen/openapi-3.1.js.

const { test }  = require('node:test');
const assert    = require('node:assert/strict');
const path      = require('node:path');
const fs        = require('node:fs');

const { generate }   = require(path.join(__dirname, '../../lib/codegen/openapi-3.1'));
const MAPPING_PATH   = path.join(__dirname, '../fixtures/sample-mapping-v1.json');
const EXPECTED_PATH  = path.join(__dirname, '../fixtures/expected-openapi-3.1.yaml');

// Load fixture once
const MAPPING = JSON.parse(fs.readFileSync(MAPPING_PATH, 'utf8'));

// ---------------------------------------------------------------------------
// (a) Non-empty YAML output from sample-mapping-v1.json
// ---------------------------------------------------------------------------

test('generate() returns a non-empty .yaml string from sample-mapping-v1.json', () => {
  const { text, ext } = generate(MAPPING);
  assert.equal(ext, '.yaml', 'extension must be .yaml');
  assert.ok(typeof text === 'string' && text.length > 0, 'text must be non-empty string');
});

// ---------------------------------------------------------------------------
// (b) Byte-determinism: two runs produce identical strings
// ---------------------------------------------------------------------------

test('generate() is byte-deterministic for the same input', () => {
  const { text: text1 } = generate(MAPPING);
  const { text: text2 } = generate(MAPPING);
  assert.equal(text1, text2, 'two runs over same mapping must produce identical output');
});

// ---------------------------------------------------------------------------
// (c) Output starts with a "# Generated by apifier" comment block
// ---------------------------------------------------------------------------

test('generate() output starts with # Generated by apifier comment block', () => {
  const { text } = generate(MAPPING);
  assert.ok(
    text.startsWith('# Generated by apifier'),
    'output must start with "# Generated by apifier"'
  );
  assert.ok(
    text.includes('Do not edit by hand'),
    'output must include "Do not edit by hand"'
  );
  assert.ok(
    text.includes(MAPPING.source.fetched_at),
    'output must include the fetched_at timestamp from mapping.source'
  );
});

// ---------------------------------------------------------------------------
// (d) `openapi: 3.1.0` declared at root
// ---------------------------------------------------------------------------

test('generate() declares openapi: 3.1.0 at root', () => {
  const { text } = generate(MAPPING);
  assert.ok(
    text.includes('openapi: 3.1.0'),
    'output must contain "openapi: 3.1.0"'
  );
});

// ---------------------------------------------------------------------------
// (e) Every endpoint's path appears under `paths:`
// ---------------------------------------------------------------------------

test('generate() emits every endpoint path under paths:', () => {
  const { text } = generate(MAPPING);
  // YAML paths section should contain each unique path
  const uniquePaths = [...new Set(MAPPING.endpoints.map(ep => ep.path))];
  for (const p of uniquePaths) {
    assert.ok(text.includes(p), `paths section must contain path '${p}'`);
  }
  assert.ok(text.includes('paths:'), 'output must have a paths: section');
});

// ---------------------------------------------------------------------------
// (f) Every model appears under `components.schemas:`
// ---------------------------------------------------------------------------

test('generate() emits every model under components.schemas:', () => {
  const { text } = generate(MAPPING);
  assert.ok(text.includes('components:'), 'output must have a components: section');
  assert.ok(text.includes('schemas:'), 'output must have a schemas: section');
  for (const model of MAPPING.models) {
    assert.ok(
      text.includes(`${model.name}:`),
      `components.schemas must contain model '${model.name}'`
    );
  }
});

// ---------------------------------------------------------------------------
// (g) Every auth scheme appears under `components.securitySchemes:`
// ---------------------------------------------------------------------------

test('generate() emits every auth scheme under components.securitySchemes:', () => {
  const { text } = generate(MAPPING);
  assert.ok(text.includes('securitySchemes:'), 'output must have a securitySchemes: section');
  for (const scheme of MAPPING.auth) {
    assert.ok(
      text.includes(`${scheme.id}:`),
      `securitySchemes must contain scheme id '${scheme.id}'`
    );
  }
});

// ---------------------------------------------------------------------------
// (h) Golden file match against tests/fixtures/expected-openapi-3.1.yaml
// ---------------------------------------------------------------------------

test('generate() output matches expected-openapi-3.1.yaml golden file byte-for-byte', () => {
  const { text } = generate(MAPPING);
  const expected = fs.readFileSync(EXPECTED_PATH, 'utf8');
  assert.equal(text, expected, 'output must match the golden fixture byte-for-byte');
});

// ---------------------------------------------------------------------------
// Additional: http-bearer auth scheme is emitted as type: http, scheme: bearer
// ---------------------------------------------------------------------------

test('generate() emits http-bearer auth as type: http, scheme: bearer', () => {
  const { text } = generate(MAPPING);
  assert.ok(text.includes('type: http'), 'bearer scheme must have type: http');
  assert.ok(text.includes('scheme: bearer'), 'bearer scheme must have scheme: bearer');
});

// ---------------------------------------------------------------------------
// Additional: operations reference security scheme ids
// ---------------------------------------------------------------------------

test('generate() emits security references for authenticated endpoints', () => {
  const { text } = generate(MAPPING);
  // The mapping's endpoints use 'bearer-jwt'; the YAML should reference that id
  assert.ok(text.includes('bearer-jwt'), 'output must reference bearer-jwt security scheme');
});

// ---------------------------------------------------------------------------
// Additional: info block contains title and version
// ---------------------------------------------------------------------------

test('generate() emits info.title and info.version from service metadata', () => {
  const { text } = generate(MAPPING);
  assert.ok(text.includes('title: Widgets API'), 'info.title must be "Widgets API"');
  // version is date-like — must be quoted but present
  assert.ok(text.includes('2026-04-12'), 'info.version must include service version');
});

// ---------------------------------------------------------------------------
// Additional: empty mapping produces valid minimal YAML
// ---------------------------------------------------------------------------

test('generate() handles minimal mapping with no endpoints, models, or auth', () => {
  const minimal = {
    schema_version: 1,
    apifier_version: '0.0.1',
    kind: 'apifier-mapping',
    service: { name: 'empty-api', version: '0.0.0' },
    source: {
      type: 'openapi',
      url: null,
      file_path: '/tmp/empty.yaml',
      fetched_at: '2026-01-01T00:00:00.000Z',
      parser: { name: 'test', version: '1' },
    },
    endpoints: [],
    models: [],
    auth: [],
    servers: [],
  };
  const { text, ext } = generate(minimal);
  assert.equal(ext, '.yaml');
  assert.ok(text.includes('openapi: 3.1.0'));
  assert.ok(text.startsWith('#'));
});
